// Generated by https://quicktype.io

import { ReactNode } from "react";

export interface Config {
	company: Company;
	navigation?: Navigation[];
	callToAction?: Action;
	mainHero: MainHero;
	product?: Product;
	features?: Features;
	pricing?: Pricing;
	about?: About;
	app: App
}

export interface About {
	sections?: {
		name: string;
		href: string;
	}[];
	socialMedia?: SocialMedia;
}

export interface SocialMedia {
	github: string | null;
	twitter: string | null;
	linkedin: string | null;
}

export interface Action {
	text: string;
	href: string;
}

export interface Company {
	name: string;
	logo?: string;
}

export interface Features {
	title: string;
	subtitle: string;
	description: string;
	items: FeaturesItem[];
}

export interface FeaturesItem {
	name: string;
	description: string;
	icon?: string;
	iconNode?: ReactNode;
}

export interface MainHero {
	title: string;
	subtitle?: string;
	description: string;
	img?: string | ReactNode;
	primaryAction?: Action;
	secondaryAction?: Action;
}

export interface Navigation {
	name: string;
	href: string;
}

export interface Pricing {
	title: string;
	items: PricingItem[];
}

export type PlanKey = 'hobby' | 'business' | 'custom';

export interface PricingItem {
	name: string;
	price: string;
	priceDetails: string;
	features: string[];
	key: PlanKey;
}

export interface Product {
	title: string;
	items: ProductItem[];
}

export interface ProductItem {
	title: string;
	description: string;
	img: string;
}

export interface App {
	siteName: string;
	title: string;
	description: string;
	locale: string;
}

const Config: Config = {
	app: {
		siteName: process.env.NEXT_PUBLIC_APP_NAME,
		title: process.env.NEXT_PUBLIC_APP_NAME,
		description: '',
		locale: 'en',
	},
	company: {
		name: process.env.NEXT_PUBLIC_APP_NAME
	},
	mainHero: {
		title: "Freelancer Rate",
		subtitle: "Calculator",
		description: "Charge what you're worth.",
	},
}

export default Config;